name: flutter_banco_douro
description: "O seu douradinho favorito!"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  camera: ^0.11.1
  flutter:
    sdk: flutter
  image: ^4.5.2
  lottie: ^3.3.1
  permission_handler: ^11.3.1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/guides/
    - assets/lotties/
